title: Harry Emeric # your name (or website title) here
logo: "/images/HarryBrooklynBridge.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description
  <br>Test 1<br>
  Second description
  <br>Test 2<br>
  <a href="www.linkedin.com/in/harryemeric">LinkedIn</a>
  <a href="https://github.com/HarryEm">github</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
